### ISSUE TITLE
Towards LinkedEarth TownHall at ICP

### ISSUE THREAD

**Issue by khider** [LinkedEarth/paleoHackathon#10]
- [ ] Release new version of Pyleoclim with the issues in the [`To Do`](https://github.com/LinkedEarth/Pyleoclim_util/projects/2)  fixed 
- [ ] Check that the new version of Pyleoclim is available on the Hub
- [ ] Run notebooks on the Hub as pass/fail test
- [ ] Add participants to the LinkedEarth organization, **THEN** 
- [ ]  to the hub 
- [ ] LinkedEarth poster with QR codes. 
- [ ] Pyleoclim poster

**Comment by CommonClimate** [comment]
For LinkedEarth poster: 
- [x] logos for Pyleoclim, GeoChronR, LiPD, JupyterHub, Python, R, Discourse, Slack, NOAA, NSF, EarthCube, JPMorgan, ONR, YouTube, PAGES
- [x] QR codes: Discourse, Training page, Tutorials (page + YouTube), LiPDverse, LiPD.net, Pyleoclim, GeoChronR, Gallery, AutoTS, PReSto, LMR.    
- [x] We are Social: email, Twitter, YouTube, GitHub, Discourse, Medium

**Comment by CommonClimate** [comment]
Pyleoclim paper:
- complete API diagram with figures
- figure : https://knowledgecaptureanddiscovery.github.io/autoTS/tutorial workflow
