### ISSUE TITLE
PaleoHack 4 promotion

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/paleoHackathon#11]
Flyer:  https://docs.google.com/document/d/1Ba_mbfzzWU0q3_sXscdYNlurv2aYCv0J9wK6xOnRj4Y/edit#
Webpage: http://linked.earth/paleoHackathon/

Diffusion strategy:

- [x] Twitter (from LE account)
- [x] Discourse
- [x] CLIMLIST
- [x]  isogeochem 
- [x] PMIP, 
- [x] Carrie’s paleo list, 
- [x] PAGES ECN + secretariat
- [x] EarthCube (Lynne Schreiber)
- [x] past PaleoHack attendees
- [x] personal contacts

**Comment by khider** [comment]
In addition, sent an email to these specific groups:

- Black in geoscience
- Society of Latinxs/Hispanics in Earth and Space Science
- Pangeo Discourse

**Comment by CommonClimate** [comment]
Excellent idea!
